


GET https://exapi-gjsy.onrender.com/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImVtYWlsIjoiYmF6aXJha2VyaWMxQGdtYWlsLmNvbSIsImlhdCI6MTc1Mjk1ODA0NX0.HEXp2lvccjGRkrGPTYp-hFk5ieM0N2RLZjN35AEWtc8
###
 

POST http://localhost:5000/updateuser
Content-Type: application/json

{
"emails":"eric.bazirake@abr.rw",
"tel":"767677",
"country":"Rwanda",
"usertype":"dfdfdfd",
"fname":"dfdffgfgfgfgf"
}

###
POST http://localhost:5000/sendemail
Content-Type: application/json

{
  "to":"yumvaelipa98@gmail.com",
  "subject":"extech test",
  "text":"password link reset"
}
### 

GET https://exapi-gjsy.onrender.com/getinfo


###
GET http://localhost:5000/getusercourse/eric.bazirake@abr.rw
