


GET https://exapi-gjsy.onrender.com/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImVtYWlsIjoiYmF6aXJha2VyaWMxQGdtYWlsLmNvbSIsImlhdCI6MTc1Mjk1ODA0NX0.HEXp2lvccjGRkrGPTYp-hFk5ieM0N2RLZjN35AEWtc8
###


POST https://exapi-gjsy.onrender.com/loginAuthe
Content-Type: application/json

{
 "passwords":"123",
 "emails":"eric.bazirake@abr.rw"
}
###

GET https://exapi-gjsy.onrender.com/protected









